### PR TITLE
fix: model cleanup not working with nested schemas (fix #227)

### LINKED ISSUE #227: Model cleanup on schema change does not work with nested schema
**Describe the bug**
When nested schema with conditions are used, model cleanup on schema change throw this error : 
`Cannot read property 'split' of undefined
`
**To Reproduce**
1. Create a nested schema with preventModelCleanupOnSchemaChange on true
2. Use condition property to conditionally display a field
3. Fulfil condition, the field display correctly
4. Unfulfil condition, formvuelate try to cleanup model and throw an error

**Expected behavior**
The field should disappear with model cleanup

**System Info**
- FormVueLate version: 3.5.0
- plugins being used with versions: 
@formvuelate/plugin-vee-validate: 3.4.0
vee-validate : 4.4.9

**Additional context**
`findNestedFormModelProp ` expect formModel on first param
https://github.com/formvuelate/formvuelate/blob/c6dca75640a3d8c88d690d82da422cd3173c7953/packages/formvuelate/src/utils/Helpers.js#L18

And we do not provide it in `findNestedFormModelProp `
https://github.com/formvuelate/formvuelate/blob/c6dca75640a3d8c88d690d82da422cd3173c7953/packages/formvuelate/src/utils/Helpers.js#L44

### PR DESCRIPTION
**Pull request by victorlambert**
Fix #227 
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/formvuelate/formvuelate/blob/main/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

**Other information:**

### CODE REVIEW

**Review by logaretm — CHANGES_REQUESTED** [review]
Thank you! This looks good but can we make this a little bit tighter by adding a test for it?

The test should fail before you've applied your fix and should pass afterwards. You can take a look at similar tests in the `packages/formvuelate/tests/unit/SchemaForm.spec.js`.

Something similar to this test here:

https://github.com/formvuelate/formvuelate/blob/main/packages/formvuelate/tests/unit/SchemaForm.spec.js#L528

**Comment by victorlambert** [comment]
Here you go, thanks for this great package !

**Review by logaretm — APPROVED** [review]
LGTM

**Review by marina-mosti — APPROVED** [review]
Thanks for the PR @victorlambert looks good

**Pull request merged**
