### PR TITLE
fix: list files in package.json to prevent git error on npm install

### PR DESCRIPTION
**Pull request by fitzhavey**
This PR fixes an issue where running `npm install` on a project with `formvuelatte` listed as a dependency fails. This is because the `.git` folder is included in the npm package.

Screenshot 2020-03-21 at 21 00 21

## Error
```
npm ERR! path /Users/michaelhavey-fitzgerald/Documents/holistic-web/repos/el-layout/node_modules/formvuelatte
npm ERR! code EISGIT
npm ERR! git /Users/michaelhavey-fitzgerald/Documents/holistic-web/repos/el-layout/node_modules/formvuelatte: Appears to be a git repo or submodule.
npm ERR! git     /Users/michaelhavey-fitzgerald/Documents/holistic-web/repos/el-layout/node_modules/formvuelatte
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelhavey-fitzgerald/.npm/_logs/2020-03-21T20_58_17_518Z-debug.log
```
Screenshot 2020-03-21 at 21 02 33

## Steps to recreate this issue
1. Have `formvuelatte` as a project's dependency and installed locally.
2. Run `npm install` again

## Solution
This issue [has been seen in other npm packages](https://www.google.com/search?q=formvuelatte+Appears+to+be+a+git+repo+or+submodule&rlz=1C5CHFA_enGB862GB862&oq=formvuelatte+Appears+to+be+a+git+repo+or+submodule), and this seems to be the generally accepted solution: https://github.com/APSL/react-native-version-number/issues/13#issuecomment-338965208

Alternatively we could simply ignore the `.git` folder with an `.npmignore` file instead of listing all the files we wish to include in this package.

## _P.S._
_I heard about this library at this year's Vue.js Amsterdam (my first ever conference and an amazing experience), I am very fond of the separation between the appearance of inputs and generation of forms - thank you for this project! 👏 🥇_

### CODE REVIEW

**Comment by marina-mosti** [comment]
Hey @michaelfitzhavey thanks for the PR, nice catch. The `.npmignore` seems like a better approach. Do you want to make the changes?

**Comment by fitzhavey** [comment]
@marina-mosti I've updated the PR to use the `.npmignore` approach but found something interesting in [npm's documentation](https://docs.npmjs.com/using-npm/developers.html#keeping-files-out-of-your-package) along the way.

It seems the `.git` folder should be ignored by npm already, so it seems strange to me that it is included in this package:

Screenshot 2020-03-23 at 03 16 36

**Comment by marina-mosti** [comment]
Thanks for the info @michaelfitzhavey 
I've looked at the docs and it seems you're right, however running `npm pack` seems to not be including the `.git` folder as intended without having to create this new `.npmignore`

I'm going to take the first approach you suggested and publish some changes in a few

**Comment by marina-mosti** [comment]
@michaelfitzhavey I've pushed the changes and updated the package, make sure to upgrade to 0.2.4 and the problem should be cleared. Thanks for the help

**Comment by fitzhavey** [comment]
Happy to help - thanks for rolling it out! 😄

**Pull request closed without merging**
